### ISSUE TITLE
Proptypes must be imported individually 

### ISSUE THREAD

**Issue by AlexOlivella** [shivekkhurana/react-native-emojicon#2]
import Proptypes from 'prop-types' must be import apart from the react import since it is like that since the new react update

**Comment by shivekkhurana** [comment]
Will fix this soon. Do you have any link to docs that show the updated usage style?

**Comment by AlexOlivella** [comment]
Here you have the docs:
https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes


El dt., 28 d’abr. 2020, 16:17, Shivek Khurana <notifications@github.com> va
escriure:

**Comment by shivekkhurana** [comment]
Hey, I checked the link you sent. The import functionality here is similar to the one outlined in the doc.

Did you mean I should use something like:
```js
import {object} from "prop-types";
```
instead of 
```js
import PropTypes from "prop-types";n
```

**Comment by AlexOlivella** [comment]
Nono,
You have to
import PropTypes from "prop-types"

**Comment by shivekkhurana** [comment]
Hmm, it's already that way:
https://github.com/shivekkhurana/react-native-emojicon/blob/880a7d27715ecd43af521c5c4228d8bbd41ecc67/index.js#L4

**Comment by shivekkhurana** [comment]
Closing for now, feel free to re-open if I missed something.
